- Jenkinsfile
- docker-images/Dockerfile
- docker-images/README
- docker/build_jaftck.sh
- docker/run_jaftck.sh
Signed-off-by: alwin.joseph <alwin.joseph@oracle.com>
> use new docker images from eclipse account

- Jenkinsfile
- LICENSE_EFTL.md
- build.xml
- docker/build_jaftck.sh
- docker/run_jaftck.sh
- release.xml
Signed-off-by: alwin.joseph <alwin.joseph@oracle.com>
> add EFT License, change bundle version, option to test prebuilt bundle

- docker/build_jaftck.sh
- docker/run_jaftck.sh
- release.xml
Signed-off-by: Gurunandan Rao <gurunandan.rao@oracle.com>
> bundle name change from  jaf to activation tck

- Jenkinsfile
- docker/build_jaftck.sh
- docker/run_jaftck.sh
Signed-off-by: alwin.joseph <alwin.joseph@oracle.com>
> test result report fix

- docs/ug/pom.xml
- docs/ug/src/main/jbake/content/attributes.conf
> update activation version in user guide

- docs/ug/src/main/jbake/content/title.adoc
> fix cp year

- docs/ug/pom.xml
- docs/ug/src/main/jbake/content/attributes.conf
- docs/ug/src/main/jbake/content/config.adoc
- docs/ug/src/main/jbake/content/config.inc
- docs/ug/src/main/jbake/content/install.adoc
- docs/ug/src/main/jbake/content/intro.adoc
- docs/ug/src/main/jbake/content/platforms.inc
Signed-off-by: alwin-joseph <alwin.joseph@oracle.com>
> userguide changes with ant corrrection

- docs/ug/src/main/jbake/content/rebuild.inc
> Update web-app schema

- docs/ug/src/main/jbake/assets/_config.yml
- docs/ug/src/main/jbake/content/attributes.conf
- docs/ug/src/main/jbake/content/config.adoc
- docs/ug/src/main/jbake/content/using-examples.inc
- docs/ug/src/main/jbake/content/using.adoc
- docs/ug/src/main/jbake/templates/footer.ftl
- tests/testsuite.jtt
Signed-off-by: alwin-joseph <alwin.joseph@oracle.com>
> userguide changes requested by ScottS

- CONTRIBUTING.md
> Add missing contributing file

- Jenkinsfile
- docker/build_activationtck.sh
- docker/run_activationtck.sh
Signed-off-by: alwin-joseph <alwin.joseph@oracle.com>
> job config changes to run prebuilt bundles

- Jenkinsfile_2.0.0_bundle
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>
> Jenkins file for bundled TCK run

- Jenkinsfile_2.0.0_bundle
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>
> TCK bundle name

- docs/ug/src/main/jbake/content/rules.adoc
Update Spec. committee e-mail list to jakarta.ee-spec@eclipse.org
> Use public list for challenge escalation

- build.xml
> bump up TCK version to 2.0.1

- Jenkinsfile
- build.xml
- docker/build_activationtck.sh
> JDK 11 build.

- Jenkinsfile
- docker/build_activationtck.sh
- docker/run_activationtck.sh
- tests/SignatureTest.html
- tests/jakarta.activation_2.1.sig
Jaf sig file update for 2.1, sig test jar update for JDK 11 support.
issue:#39
CI run: https://ci.eclipse.org/jakartaee-tck/job/guru/job/jaf-tck-guru/job/update-sigtest/10/
> update signature jars and signature files for activation 2.1

- .gitignore
- docker/run_activationtck.sh
- release.xml
Relates to https://github.com/eclipse-ee4j/jaf-tck/issues/48
The bundled zip did not contain the classes.
> Jenkins failing to execute tests

- docker/run_activationtck.sh
> upgrade glassfish top directory.

- Jenkinsfile
- docker/run_activationtck.sh
update scripts to use new docker image with JDK 17.
> update scripts to use new docker image with JDK 17.

- tests/api/SignatureTest.html
> fix ignore JDK class for JDK 17 runs.

- CONTRIBUTING.md
- NOTICE
- QuickStart.txt
- build.xml
- docs/ug/pom.xml
- docs/ug/src/main/jbake/assets/_config.yml
- docs/ug/src/main/jbake/content/attributes.conf
> update version to 2.1.1-SNAPSHOT, update pointers to jakartaee/jaf..

- build.xml
- release.xml
> api98 part2

- Jenkinsfile
- docker/build_activationtck.sh
- docker/run_activationtck.sh
- lib/ts.jte
- lib/ts.pluggability.jte
jdk21 support with security manager disabled.
CI run - https://ci.eclipse.org/jakartaee-tck/job/guru/job/jaf-tck-guru/job/security-manager/10/
> jdk21 support with security manager disabled.
